#!/usr/bin/env python3
"""Recompute every screening delta from RESULTS.csv.

Added 2026-08-05, after the seed-1111 screening anchor moved from 0.1725 to
0.1728 when the wave-1 results tree was cleared for the confirmation eval.
Rather than re-anchoring twenty-six delta columns by hand, every delta in
PROJECT_PLAN.md and in the vault tables is regenerated from the CSV by this
script, so the tables and the source of truth cannot drift apart again.

Two delta columns, deliberately:

  vs anchor  -- against seedfloor_1111_chn, the historical reference. Kept
                because every ranking decision in the project was made on it,
                including the Batch B selection.
  vs mean    -- against the three-seed baseline mean, which is the column the
                2026-08-05 anchor-bias reading says should have been used.

The two disagree by 0.0048 at screening budget. That disagreement is the
finding, so both columns are printed and neither is dropped.

Usage:
    python scripts/recompute_deltas.py                # markdown tables
    python scripts/recompute_deltas.py --csv          # flat CSV
    python scripts/recompute_deltas.py --n-samples 50 # confirmation budget
"""

import argparse
import csv
import os
import sys
from collections import OrderedDict

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RESULTS = os.path.join(REPO, "RESULTS.csv")

BASELINES = ["seedfloor_1111_chn", "seedfloor_2222_chn", "seedfloor_3333_chn"]
ANCHOR = "seedfloor_1111_chn"

# Batch label -> (heading, sort key). tier3b rows are multi-seed candidates and
# are read by paired per-seed difference, not against the floor, so they get
# their own section rather than a delta column against the seed-1111 anchor.
SECTIONS = OrderedDict(
    [
        ("tier1", "Tier 1"),
        ("tier2", "Tier 2"),
        ("tier3a", "Tier 3, Batch A"),
        ("tier3b", "Tier 3, Batch B (multi-seed)"),
        ("stage1", "Stage 1 reference"),
    ]
)


def load(path, n_samples, language="chn"):
    rows = []
    with open(path, newline="", encoding="utf-8") as fh:
        for row in csv.DictReader(fh):
            if row["language"] != language:
                continue
            if int(row["n_samples"]) != n_samples:
                continue
            for key in ("l1", "s_iou", "ssim"):
                row[key] = float(row[key]) if row[key] else None
            row["seed"] = int(row["seed"])
            rows.append(row)
    return rows


def floor(values):
    """Spread across the baseline seeds: max - min, the project's floor."""
    return max(values) - min(values)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--results", default=RESULTS)
    ap.add_argument("--n-samples", type=int, default=3)
    ap.add_argument("--language", default="chn")
    ap.add_argument("--csv", action="store_true", help="flat CSV instead of markdown")
    args = ap.parse_args()

    rows = load(args.results, args.n_samples, args.language)
    if not rows:
        sys.exit(f"no {args.language} rows at n_samples={args.n_samples} in {args.results}")

    base = {r["name_exp"]: r for r in rows if r["name_exp"] in BASELINES}
    missing = [b for b in BASELINES if b not in base]
    if missing:
        sys.exit(f"missing baseline rows at n_samples={args.n_samples}: {missing}")

    anchor_l1 = base[ANCHOR]["l1"]
    anchor_iou = base[ANCHOR]["s_iou"]
    mean_l1 = sum(base[b]["l1"] for b in BASELINES) / 3
    mean_iou = sum(base[b]["s_iou"] for b in BASELINES) / 3
    floor_l1 = floor([base[b]["l1"] for b in BASELINES])
    floor_iou = floor([base[b]["s_iou"] for b in BASELINES])

    cands = [r for r in rows if r["name_exp"] not in BASELINES]

    if args.csv:
        w = csv.writer(sys.stdout)
        w.writerow(
            ["name_exp", "batch", "seed", "epoch", "l1", "s_iou",
             "d_l1_anchor", "d_l1_mean", "d_iou_anchor", "d_iou_mean",
             "inside_l1_floor", "inside_iou_floor"]
        )
        for r in sorted(cands, key=lambda r: r["l1"]):
            d_a, d_m = r["l1"] - anchor_l1, r["l1"] - mean_l1
            i_a, i_m = r["s_iou"] - anchor_iou, r["s_iou"] - mean_iou
            w.writerow([
                r["name_exp"], r["batch"], r["seed"], r["epoch"],
                f"{r['l1']:.4f}", f"{r['s_iou']:.4f}",
                f"{d_a:+.4f}", f"{d_m:+.4f}", f"{i_a:+.4f}", f"{i_m:+.4f}",
                abs(d_a) < floor_l1, abs(i_a) < floor_iou,
            ])
        return

    print(f"# Screening deltas, recomputed from RESULTS.csv (n_samples={args.n_samples})\n")
    print("Generated by `scripts/recompute_deltas.py`. Do not hand-edit the numbers below;")
    print("regenerate them. Every value is derived from the CSV, which is itself generated")
    print("from the per-font eval output by `scripts/build_results_table.py`.\n")
    print("| Reference | L1 | s-IoU |")
    print("|---|---|---|")
    for b in BASELINES:
        print(f"| `{b}` | {base[b]['l1']:.4f} | {base[b]['s_iou']:.4f} |")
    print(f"| **Three-seed mean** | **{mean_l1:.4f}** | **{mean_iou:.4f}** |")
    print(f"| **Seed spread (the floor)** | **{floor_l1:.4f}** | **{floor_iou:.4f}** |")
    print(f"\nAnchor is `{ANCHOR}`, which sits {anchor_l1 - mean_l1:+.4f} from the mean in L1.\n")

    for batch, heading in SECTIONS.items():
        sel = [r for r in cands if r["batch"] == batch]
        if not sel:
            continue
        print(f"\n## {heading}\n")
        if batch == "tier3b":
            print("Read by paired per-seed difference, not against the floor: the floor is the")
            print("baseline's own spread and is the quantity a multi-seed design replaces.\n")
        print("| Run | Seed | Epoch | L1 ↓ | vs anchor | vs mean | s-IoU ↑ | vs mean |")
        print("|---|---|---|---|---|---|---|---|")
        for r in sorted(sel, key=lambda r: (r["seed"], r["l1"])):
            print(
                f"| `{r['name_exp']}` | {r['seed']} | {r['epoch']} | {r['l1']:.4f} | "
                f"{r['l1'] - anchor_l1:+.4f} | {r['l1'] - mean_l1:+.4f} | "
                f"{r['s_iou']:.4f} | {r['s_iou'] - mean_iou:+.4f} |"
            )

    single = [r for r in cands if r["batch"] in ("tier1", "tier2", "tier3a")]
    beat_anchor = sum(1 for r in single if r["l1"] < anchor_l1)
    beat_mean = sum(1 for r in single if r["l1"] < mean_l1)
    print(f"\n## The anchor bias, recomputed\n")
    print(f"- {beat_anchor} of {len(single)} single-seed candidates beat the anchor.")
    print(f"- {beat_mean} of {len(single)} beat the three-seed mean.")
    if single:
        best = min(single, key=lambda r: r["l1"])
        print(f"- Best single-seed candidate: `{best['name_exp']}` at {best['l1']:.4f}, "
              f"{best['l1'] - mean_l1:+.4f} against the mean.")
        span = floor([r["l1"] for r in single])
        print(f"- Candidate L1 span: {span:.4f}, against a baseline seed span of {floor_l1:.4f}.")


if __name__ == "__main__":
    main()
